trigger:
- main

pool:
  name: Default

steps:
- task: UseDotNet@2
  displayName: "Instalación SDK"
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  displayName: "Compilación"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo-taller'

- task: DotNetCoreCLI@2
  displayName: "Publicación"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo-taller'

- task: DotNetCoreCLI@2
  displayName: "Pruebas"
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    publishTestResults: true
